spring.application.name=AvalieKintal
spring.datasource.url=jdbc:postgresql://localhost:5432/avalie_kintal
spring.datasource.username=postgres
spring.datasource.password=Juca047!
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.flyway.enabled=true
spring.flyway.locations=classpath:migration

jwt.public.key=classpath:keys/public.pem
jwt.private.key=classpath:keys/private.pem



